services:
  traefik:
    image: "traefik:v3.7.11"
    container_name: "traefik"
    restart: unless-stopped
    command:
      # - "--log.level=DEBUG"
      - "--accesslog"
      - "--accesslog.filepath=/var/log/traefik/access.log"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"

      - "--experimental.localplugins.bouncer.modulename=github.com/david-garcia-garcia/crowdsec-bouncer-traefik-plugin"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./../../:/plugins-local/src/github.com/david-garcia-garcia/crowdsec-bouncer-traefik-plugin
    ports:
      - 80:80
      - 8080:8080

  whoami-foo:
    image: traefik/whoami
    container_name: "simple-service-foo-alone"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.router-foo.rule=Path(`/foo`)"
      - "traefik.http.routers.router-foo.entrypoints=web"
      - "traefik.http.routers.router-foo.middlewares=crowdsec@docker" 
      - "traefik.http.services.service-foo.loadbalancer.server.port=80"

      - "traefik.http.middlewares.crowdsec.plugin.bouncer.bouncerEnabled=true"
      # - "traefik.http.middlewares.crowdsec.plugin.bouncer.logLevel=DEBUG"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.lapiMode=alone"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.lapiCapiMachineId=FIXME"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.LapiCapiPassword=FIXME"
      - "traefik.http.middlewares.crowdsec.plugin.bouncer.lapiCapiScenarios=crowdsecurity/sshd,crowdsecurity/asterisk_bf,crowdsecurity/asterisk_user_enum,crowdsecurity/base-http-scenarios"

