http:
  routers:
    to-whoami-http-service:
      rule: "PathPrefix(`/`)"
      service: whoami-service
      middlewares:
        - "crowdsec-whoami"
      entryPoints:
        - web
  
  services:
    whoami-service:
      loadBalancer:
        servers:
        - url: "http://localhost:9000/"

  middlewares:
    crowdsec-whoami: 
      plugin:
        bouncer:
          bouncerEnabled: true
          lapiEnabled: true
          lapiKey: "whoami-demo"
          lapiUpdateIntervalSeconds: 60
          lapiMode: live
          loglevel: "DEBUG"
          lapiScheme: https
          lapiHost: localhost:8080
          lapiTlsInsecureVerify: false
          lapiTlsCertificateAuthorityFile: /etc/traefik/crowdsec-certs/inter.pem
          lapiTlsClientCertificateFile: /etc/traefik/crowdsec-certs/bouncer.pem
          lapiTlsClientKeyFile: /etc/traefik/crowdsec-certs/bouncer-key.pem
