apiVersion: traefik.io/v1alpha1
kind: Middleware
metadata:
    name: bouncer
    namespace: traefik
spec:
    plugin:
        bouncer:
            LapiKey: 40796d93c2958f9e58345514e67740e5
            Enabled: "true"
            logLevel: DEBUG
            lapiMode: live
            lapiHost: crowdsec-service.crowdsec.svc.cluster.local:8080
            lapiScheme: http
